services:
  web:
    build: ./back_generador/
    container_name: django_backend
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=colaborativodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=071104
      - CORS_ALLOWED_ORIGINS=http://localhost:4000,http://angular-app:4000
    volumes:
      - ./back_generador:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - angular-app
    networks:
      - backend
      - frontend
    command: >
      sh -c "python manage.py migrate &&
           exec daphne -b 0.0.0.0 -p 8000 ${ASGI_APP:-diagramador.asgi:application}"

  angular-app:
    build: ./front_generador_bd/
    container_name: angular_frontend
    ports:
      - "4000:4000"
    environment:
      - API_URL=http://web:8000
    networks:
      - frontend
      - backend

networks:
  backend:
    external: true
  frontend:
    driver: bridge