services:
  web:
    build: ./back_generador/
    container_name: django_backend
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=colaborativodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=071104
      - CORS_ALLOWED_ORIGINS=http://localhost:4000,http://angular-app:4000
    volumes:
      - ./back_generador:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - angular-app
    networks:
      - backend
      - frontend
    #command: >
    #  sh -c "python manage.py migrate &&
    #       exec daphne -b 0.0.0.0 -p 8000 ${ASGI_APP:-diagramador.asgi:application}"
    command: >
     sh -c "python manage.py makemigrations && python manage.py migrate &&
         exec daphne -b 0.0.0.0 -p 8000 diagramador.asgi:application"


  angular-app:
    build: ./front_generador_bd/
    container_name: angular_frontend
    ports:
      - "4000:4000"
    environment:
      - API_URL=http://web:8000
      - GENERATOR_URL=http://generator:8080   #
    networks:
      - frontend
      - backend

  generator:
    build: ./api-generator/api-generator/   # 👈 Carpeta donde está tu Dockerfile del generador
    container_name: spring_generator
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=America/La_Paz
    networks:
      - frontend
      - backend

networks:
  backend:
    external: true
  frontend:
    driver: bridge