# Generated by Django 5.0.14 on 2025-09-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='name',
            field=models.CharField(default='Untitled', max_length=120, unique=True),
        ),
    ]
