# Generated by Django 5.0.14 on 2025-09-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborativo', '0002_alter_diagram_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
